# Pytorch Fundamentals

<h3>variables and graidents</h3>

<h3>2.1 Variables </h3>
<ul>
    <li>* Variable warps a tensor </li>
    <li>* Allow accumulation of tensor</li>
</ul>


</br>


In [3]:
import torch
from torch.autograd import Variable

In [7]:
# requires_grad : 
a = Variable(torch.ones(2,2), requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

# Gradients

<b> Defination </b>
* Allow calculation of gradients w.r.t the variable

In [10]:
x = Variable(torch.ones(2), requires_grad = True)
x

tensor([1., 1.], requires_grad=True)

In [11]:
# Equation
y = 5 * (x + 1) **2

In [12]:
print(y)

tensor([20., 20.], grad_fn=<MulBackward0>)


<b> backward should be only calculated to the scalar (i.e 1-element tensor) or with gradient w.r.t variable </b>

* reducing y to scalar

In [31]:
count = y.size()[0]
o = 1/count * torch.sum(y)

In [32]:
o

tensor(20., grad_fn=<MulBackward0>)

In [19]:
o.backward()

In [20]:
x.grad

tensor([10., 10.])