In [3]:
import torch

In [4]:
# Creating torch tensor
arr = [[1,2],[4,5]]
torch.Tensor(arr)

tensor([[1., 2.],
        [4., 5.]])

In [10]:
# Create a matrix of default values
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [11]:
# creating random numbers
torch.rand(2,2)

tensor([[0.3546, 0.4494],
        [0.1412, 0.0991]])

In [13]:
# creating a seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [15]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [16]:
# set gpu seed
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

# numpy and torch bridge

In [17]:
import numpy as np

In [22]:
np_arr = np.array([[1,2], [4,5]])
print(type(np_arr))

<class 'numpy.ndarray'>


In [23]:
torch_arr = torch.from_numpy(np_arr)
print(type(torch_arr))

<class 'torch.Tensor'>


In [21]:
torch_arr

tensor([[1, 2],
        [4, 5]])

In [25]:
np_int = np.ones((2,2), dtype=np.int8)
print(type(np_int))

<class 'numpy.ndarray'>


In [27]:
torch_int = torch.from_numpy(np_int)
print(type(torch_int))

<class 'torch.Tensor'>


In [29]:
np_float = np.ones((2,2), dtype=np.int8)
print(type(np_int))

<class 'numpy.ndarray'>


In [30]:
torch_float = torch.from_numpy(np_float)
print(type(torch_int))

<class 'torch.Tensor'>


# Convert torch tensor to numpy array

In [36]:
torch_tensor = torch.ones((2,2))
print(type(torch_tensor))

<class 'torch.Tensor'>


In [34]:
np_array = torch_tensor.numpy()

In [35]:
print(type(np_array))

<class 'numpy.ndarray'>


# moving torch tensor to GPU

In [37]:
# cpu 

In [38]:
torch_tensor = torch.ones(2,2)

In [40]:
# moving to gpu
if torch.cuda.is_available():
    torch_tensor.cuda()

In [44]:
# from gpu to cpu
torch_tensor.cpu()

tensor([[1., 1.],
        [1., 1.]])

# Resizing Tensor

In [48]:
a = torch.ones((2,2))

In [49]:
print(a.size())

torch.Size([2, 2])


In [51]:
a.view(4)

tensor([1., 1., 1., 1.])

# Element wise addition

In [54]:
b = torch.ones((2,2))
c = a + b

In [55]:
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [56]:
d = torch.add(a, b)

In [60]:
# inplace addition
c.add_(a)
print(c)

tensor([[4., 4.],
        [4., 4.]])


In [63]:
# substraction elementwise using inplace
c.sub_(b)

tensor([[1., 1.],
        [1., 1.]])

In [77]:
e = torch.tensor([0,0])
e.t_()

tensor([0, 0])

In [83]:
torch.mul(c,a)
print(c)
c.mul_(a)
print(c)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [84]:
# divide

In [85]:
v = a/b

In [88]:
# using torch
v = torch.div(a,b)

In [87]:
# inplace
a.div_(b)

tensor([[1., 1.],
        [1., 1.]])

In [106]:
num = torch.arange(1,11,1, dtype=torch.float32)
num.mul_(torch.ones(10))
num.size()

torch.Size([10])

In [111]:
num.mean(dim=0)

tensor(5.5000)

In [114]:
a = num * torch.ones(2,10)
# 1: row, 0: column
a.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [116]:
a.std(dim=1)

tensor([3.0277, 3.0277])